task: docred #re3d #scierc #scirex #scierc 
data_dir: 
output_dir: "saved_models"
max_length: 1024
max_span_length: 8
span_hidden_size: 150
train_batch_size: 8
eval_batch_size: 8
negative_samples_per_batch: 10
learning_rate: 1e-4
warmup_proportion: 0.1
num_epoch: 100
eval_per_epoch: 1
debug: False
do_train: False
do_eval: False
do_predict: True
train_shuffle: True
entity_classes_json: /home/shearman/Desktop/work/NER-module/data/docred_pure/entity_classes.json
longformer:
  config: /home/shearman/Desktop/work/NER-module/longformer/config
  model: /home/shearman/Desktop/work/NER-module/longformer/model
  tokenizer: /home/shearman/Desktop/work/NER-module/longformer/tokenizer
  autotokenizer: /home/shearman/Desktop/work/NER-module/longformer/autotokenizer
seed: 1234
clearml_dataset_project_name: datasets/PURE #datasets/sci-erc #datasets/scirex #datasets/sci-erc 
clearml_dataset_name: DOCRED #re3d #processed_json #scirex-doc #processed_json 
clearml_dataset_tags: []
task_tags: []
gpu: 0
remote: False
early_stopping: False
checkpointing: True
trained_model_path: 
ner_trained_model_path: /home/shearman/Desktop/work/NER-module/spanNER/models/best_ner.ckpt
ner_confidence: 0.70
queue: queue-1xV100-32ram
